name: Generate metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.svg
          base: ""
          config_timezone: Europe/Tallinn
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
